name:               miso-tutorial-app-server
version:            '0.1.0.0'
synopsis:           The server side of an example SPA in GHCJS + Miso.
category:           Web
license:            BSD3

dependencies:
- aeson
- base
- bytestring
  #- ghcjs-base
- miso
- servant
- servant-server
- utf8-string
- network-uri
- http-types
- warp
- wai
- lucid
- wai-logger
- containers
- stm
- transformers

executables:
  miso-tutorial-app-server:
    main:           Main.hs
    source-dirs:
    - ./
    - ../shared
